//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public string Text { get; set; }
        public System.DateTime Time { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
        public bool IsPrivate { get; set; }
        public int UserSendId { get; set; }
        public int UserReceiveId { get; set; }
    
        public virtual User UserReceiver { get; set; }
        public virtual User UserSender { get; set; }
    }
}
