//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ReceiveMessages = new HashSet<Message>();
            this.SendMessages = new HashSet<Message>();
            this.Songs = new HashSet<Song>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
    
        public virtual ICollection<Message> ReceiveMessages { get; set; }
        public virtual ICollection<Message> SendMessages { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Song> Songs { get; set; }
    }
}
